# Pre-install dependencies for Copilot coding agent
setup:
  - run: corepack enable
  - run: corepack prepare pnpm@latest --activate
  - run: pnpm install --frozen-lockfile
  - run: pnpm typecheck
  - run: pnpm lint
  - run: pnpm build
