version = 1

# Enable JavaScript/TypeScript analyzer
[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  # Runtime version for Node.js — use 22.x if your repo is on Node 22
  runtime_version = "22.x"
  test_frameworks = ["jest", "playwright"]

# Enable Dockerfile analyzer
[[analyzers]]
name = "docker"
enabled = true

# Enable Shell analyzer
[[analyzers]]
name = "shell"
enabled = true

# Enable Secrets analyzer (detects API keys, tokens, etc.)
[[analyzers]]
name = "secrets"
enabled = true

# Prettier transformer for consistent formatting
[[transformers]]
name = "prettier"
enabled = true

# ESLint transformer for lint rules
[[transformers]]
name = "eslint"
enabled = true
