version = 1

[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
  dialect = "typescript"
  module_system = "es-modules"   # valid: commonjs | es-modules | amd

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
  [analyzers.meta]
  command = "pnpm test:coverage"

[[transformers]]
name = "prettier"
enabled = true

[ignore]
patterns = [
  "node_modules/**",
  ".next/**",
  "out/**",
  "dist/**",
  "build/**",
  "coverage/**",
  ".cache/**",
  "*.lock",
  "*.d.ts",
]

[report]
severity = "error"
