version = 1

[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
  # Project uses TypeScript and ES modules (Next.js / modern JS). Valid
  # `environment` values include: nodejs, browser, jest, mocha, jasmine,
  # jquery, mongo, cypress, vitest. Use the closest match for your repo.
  dialect = "typescript"
  module_system = "es-modules"   # valid: commonjs | es-modules | amd
  environment = "nodejs"

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
  # Enabled without custom `meta` to avoid invalid option errors. If you
  # want DeepSource to run a custom coverage command (for example,
  # `pnpm test:coverage`) or parse a coverage report, we should add the
  # supported `meta` keys from the DeepSource docs. Tell me the exact
  # coverage runner you use and I will fetch the docs and wire it up.

[[transformers]]
name = "prettier"
enabled = true

[ignore]
patterns = [
  "node_modules/**",
  ".next/**",
  "out/**",
  "dist/**",
  "build/**",
  "coverage/**",
  ".cache/**",
  "*.lock",
  "*.d.ts",
]

[report]
severity = "error"
