title = "scheduler gitleaks config"

[extend]
useDefault = true

[allowlist]
files = [
  ".env.example",
  ".next/**/*",
  "**/.next/**/*"
]
regexes = [ "(?i)dummy|example|placeholder|test_key" ]
paths = [
  ".*\\.next/.*",
  ".*/\\.next/.*"
]
