name: CI - pnpm lint, typecheck, test, build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  node-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.17.1
          # Do not run install here; we run an explicit, controlled install below.
          # This prevents the action from failing early when it can't detect a lockfile path.
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

      - name: Test
        run: pnpm run test:run
        env:
          NODE_ENV: test

      - name: Test Firestore Rules
        run: pnpm run test:rules
        env:
          NODE_ENV: test

      - name: Build
        run: pnpm run build
        env:
          NEXT_TELEMETRY_DISABLED: "1"
