name: DeepSource
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: DeepSource Scan
        uses: deepsourcelabs/test-action@v1
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
